export const ANALYTICS_EVENT_NAMES = [
  "page_view",
  "landing_view",
  "landing_start_click",
  "landing_cta_click",
  "onboarding_entry_click",
  "nav_click",
  "decisions_view",
  "decisions_intro_impression",
  "decisions_hero_impression",
  "alerts_view",
  "library_view",
  "watchlist_view",
  "episodes_view",
  "history_view",
  "decision_replay_view",
  "weekly_digest_view",
  "account_view",
  "onboarding_view",
  "onboarding_start",
  "onboarding_step_complete",
  "onboarding_complete",
  "preference_update",
  "judgment_card_impression",
  "judgment_card_click",
  "judgment_card_expand",
  "judgment_card_locked_cta_click",
  "decision_calculator_open",
  "decision_calculator_submit",
  "decision_calculator_result_view",
  "decision_save",
  "decision_action_click",
  "decision_remove",
  "outcome_update",
  "outcome_reminder_impression",
  "outcome_reminder_click",
  "outcome_quick_submit",
  "outcome_reminder_to_replay_click",
  "alert_impression",
  "alert_click",
  "alert_mark_read",
  "alert_dismiss",
  "weekly_digest_alert_click",
  "outcome_reminder_alert_click",
  "decision_replay_insight_impression",
  "decision_replay_from_history_click",
  "library_search",
  "library_filter_change",
  "library_sort_change",
  "library_card_click",
  "library_pref_personalized_impression",
  "watchlist_add",
  "watchlist_remove",
  "watchlist_filter_change",
  "watchlist_card_click",
  "next_best_decision_impression",
  "next_best_decision_click",
  "paywall_view",
  "subscribe_cta_click",
  "checkout_started",
  "checkout_completed",
  "billing_portal_open",
  "weekly_digest_open",
  "weekly_digest_item_click",
  "generate_card_submit",
  "generate_card_outcome"
] as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENT_NAMES)[number];

export const ANALYTICS_PAGE_NAMES = [
  "/",
  "/decisions",
  "/alerts",
  "/decisions/library",
  "/saved",
  "/episodes",
  "/history",
  "/history/replay",
  "/weekly-decisions",
  "/account",
  "/onboarding"
] as const;

export type AnalyticsPageName = (typeof ANALYTICS_PAGE_NAMES)[number];

export const isAnalyticsEventName = (value: unknown): value is AnalyticsEventName => {
  return typeof value === "string" && ANALYTICS_EVENT_NAMES.includes(value as AnalyticsEventName);
};
